import type { Employee } from '@/modules/employees/types'

// Demo-only employees concatenated onto MOCK_EMPLOYEES when SEED_MODE=demo.
// Roughly 12 US / 10 India / 3 Colombia — enough scale to populate the
// feed, team-rhythm, and program-health surfaces without being overwhelming.
// IDs use the emp_02x / emp_04x / emp_05x ranges so they can't collide
// with baseline (emp_001–emp_011) or the system actor (emp_system).
export const DEMO_EMPLOYEES: Employee[] = [
  // ── US (12) ──────────────────────────────────────────────────────────
  {
    id: 'emp_020',
    name: 'Michael Brown',
    email: 'michael.brown@novo.co',
    geo: 'US',
    manager_id: 'emp_001',
    role_title: 'Head of Product',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Product',
    is_department_head: true,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_021',
    name: 'Lauren Park',
    email: 'lauren.park@novo.co',
    geo: 'US',
    manager_id: 'emp_001',
    role_title: 'Head of Marketing',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Marketing',
    is_department_head: true,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_022',
    name: 'David Kim',
    email: 'david.kim@novo.co',
    geo: 'US',
    manager_id: 'emp_001',
    role_title: 'VP Sales',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Sales',
    is_department_head: true,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_023',
    name: 'Elena Vasquez',
    email: 'elena.vasquez@novo.co',
    geo: 'US',
    manager_id: 'emp_001',
    role_title: 'Director of Design',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Design',
    is_department_head: true,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_024',
    name: 'Thomas Wright',
    email: 'thomas.wright@novo.co',
    geo: 'US',
    manager_id: 'emp_005',
    role_title: 'Engineering Manager',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_025',
    name: 'Nina Rodriguez',
    email: 'nina.rodriguez@novo.co',
    geo: 'US',
    manager_id: 'emp_024',
    role_title: 'Senior Software Engineer',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_026',
    name: 'Marcus Johnson',
    email: 'marcus.johnson@novo.co',
    geo: 'US',
    manager_id: 'emp_020',
    role_title: 'Product Manager',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'team_only',
    department: 'Product',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_027',
    name: 'Rachel Lee',
    email: 'rachel.lee@novo.co',
    geo: 'US',
    manager_id: 'emp_021',
    role_title: 'Marketing Manager',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Marketing',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_028',
    name: 'Chris Patel',
    email: 'chris.patel@novo.co',
    geo: 'US',
    manager_id: 'emp_022',
    role_title: 'Account Executive',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Sales',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_029',
    name: 'Tara Singh',
    email: 'tara.singh@novo.co',
    geo: 'US',
    manager_id: 'emp_023',
    role_title: 'Senior Product Designer',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Design',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_030',
    name: 'Ben Wilson',
    email: 'ben.wilson@novo.co',
    geo: 'US',
    manager_id: 'emp_001',
    role_title: 'Head of Customer Success',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Customer Success',
    is_department_head: true,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_031',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@novo.co',
    geo: 'US',
    manager_id: 'emp_020',
    role_title: 'Data Analyst',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Product',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },

  // ── India (10) ────────────────────────────────────────────────────────
  {
    id: 'emp_040',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@novo.co',
    geo: 'India',
    manager_id: 'emp_008',
    role_title: 'Engineering Manager',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_041',
    name: 'Ananya Singh',
    email: 'ananya.singh@novo.co',
    geo: 'India',
    manager_id: 'emp_040',
    role_title: 'Software Engineer',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_042',
    name: 'Vikram Rao',
    email: 'vikram.rao@novo.co',
    geo: 'India',
    manager_id: 'emp_040',
    role_title: 'Software Engineer',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_043',
    name: 'Deepak Kumar',
    email: 'deepak.kumar@novo.co',
    geo: 'India',
    manager_id: 'emp_008',
    role_title: 'Software Engineer',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'team_only',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_044',
    name: 'Meera Iyer',
    email: 'meera.iyer@novo.co',
    geo: 'India',
    manager_id: 'emp_008',
    role_title: 'Senior Software Engineer',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_045',
    name: 'Kavya Nair',
    email: 'kavya.nair@novo.co',
    geo: 'India',
    manager_id: 'emp_008',
    role_title: 'QA Engineer',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Engineering',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_046',
    name: 'Suresh Menon',
    email: 'suresh.menon@novo.co',
    geo: 'India',
    manager_id: 'emp_001',
    role_title: 'Operations Manager',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Operations',
    is_department_head: true,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_047',
    name: 'Anjali Desai',
    email: 'anjali.desai@novo.co',
    geo: 'India',
    manager_id: 'emp_046',
    role_title: 'Operations Analyst',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Operations',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_048',
    name: 'Neha Gupta',
    email: 'neha.gupta@novo.co',
    geo: 'India',
    manager_id: 'emp_001',
    role_title: 'Head of Customer Support',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Customer Success',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_049',
    name: 'Varun Malhotra',
    email: 'varun.malhotra@novo.co',
    geo: 'India',
    manager_id: 'emp_048',
    role_title: 'Support Specialist',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'private',
    department: 'Customer Success',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },

  // ── Colombia (3) ──────────────────────────────────────────────────────
  {
    id: 'emp_050',
    name: 'Diego Ramirez',
    email: 'diego.ramirez@novo.co',
    geo: 'Colombia',
    manager_id: 'emp_010',
    role_title: 'Operations Analyst',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Operations',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_051',
    name: 'Camila Silva',
    email: 'camila.silva@novo.co',
    geo: 'Colombia',
    manager_id: 'emp_010',
    role_title: 'Account Manager',
    active: true,
    employment_type: 'employee',
    recognition_preference: 'public',
    department: 'Operations',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
  {
    id: 'emp_052',
    name: 'Isabella Perez',
    email: 'isabella.perez@novo.co',
    geo: 'Colombia',
    manager_id: 'emp_010',
    role_title: 'Support Specialist',
    active: true,
    employment_type: 'contractor',
    recognition_preference: 'public',
    department: 'Operations',
    is_department_head: false,
    is_people_team_rep: false,
    is_committee_member: false,
    tier2_assignments_count: 0,
  },
]
